### ISSUE TITLE
📝: Adding CITATION.cff to repo

### ISSUE THREAD

**Issue by jossmoff** [polywit/polywit#21]
### Polywit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main`

### Documentation problem

Github provides the ability to add a citation file to your repository to automatically generate the bibtex entry on your repo, [see here](https://citation-file-format.github.io/).

### Suggested fix for documentation

We add the CITATION.cff file and want the bibtex entry to look something like
```latex
@software{poylwit,
  author = {{Joss Moffatt and Tong Wu and Lucas Cordeiro and Peter Schrammel}},
  license = {MIT},
  title = {{polywit: The poly-language execution-based violation-witness validator}},
  url = {https://github.com/polywit/polywit}
}
```

**Comment by jossmoff** [comment]
@lucasccordeiro I just found out about this feature first of all:
- Are the authors okay?
- Shall I raise a similar issue in ESBMC?

**Comment by lucasccordeiro** [comment]
> Are the authors okay?

That looks good to me ;-)

**Comment by lucasccordeiro** [comment]
> Shall I raise a similar issue in ESBMC?

Yes, please.
